---
- name: Authorized key
  hosts: ubuntu

  tasks:
    - name: Set authorized key taken from file
      ansible.posix.authorized_key:
        user: mihai
        state: present
        key: "{{ lookup('file', '../keys/id_ansible.pub') }}"
