---
- name: Vault variables
  hosts: ubuntu
  gather_facts: true

  tasks:
    - name: Print the gateway for each host when defined
      ansible.builtin.debug:
        msg: System {{ inventory_hostname }} has gateway

    - name: Display all variables/facts known for a host
      ansible.builtin.debug:
        var: hostvars[inventory_hostname]

    - name: Show the remote machine memory
      ansible.builtin.debug:
        msg: "Total memory: {{ ansible_facts.memory_mb.real.total }}"
